spring:
  application:
    name: olxconnect

  mail:
    host: smtp.dpoczta.pl
    port: 587
    username: ${SPRING_MAIL_USERNAME} # Użytkownik do serwera SMTP (Heroku Config Vars)
    password: ${SPRING_MAIL_PASSWORD} # Hasło do serwera SMTP (Heroku Config Vars)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true

  datasource:
    url: ${DATABASE_URL} # URL bazy danych ustawiony w Heroku Config Vars
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME} # Jeśli nie jest częścią DATABASE_URL
    password: ${DATABASE_PASSWORD} # Jeśli nie jest częścią DATABASE_URL
    hikari:
      maximum-pool-size: 16 # Limit połączeń do bazy danych

  jpa:
    hibernate:
      ddl-auto: update # Zmieniaj tylko podczas developmentu
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

olx:
  api:
    base-url: ${OLX_API_BASE_URL} # Podstawowy URL API OLX (Heroku Config Vars)
  client_id: ${OLX_CLIENT_ID} # Klucz klienta (Heroku Config Vars)
  client_secret: ${OLX_CLIENT_SECRET} # Sekret klienta (Heroku Config Vars)
  redirect_uri: ${OLX_REDIRECT_URI} # URL przekierowania (Heroku Config Vars)

mailersend:
  api:
    token: ${MAILERSEND_API_TOKEN} # Token API Mailersend (Heroku Config Vars)

logging:
  level:
    root: DEBUG
    org.springframework.mail: TRACE
    org.springframework.boot.autoconfigure.mail: TRACE
