spring:
  application:
    name: olxconnect

  mail:
    host: smtp.dpoczta.pl
    port: 25
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

mailersend:
  api-key: ${MAILERSEND_API_KEY}

olx:
  client_id: ${OLX_CLIENT_ID}
  client_secret: ${OLX_CLIENT_SECRET}
  redirect_uri: ${OLX_REDIRECT_URI}

logging:
  level:
    root: DEBUG
    org.springframework.mail: TRACE
    org.springframework.boot.autoconfigure.mail: TRACE
