spring:
  application:
    name: olxconnect

  mail:
    host: smtp.dpoczta.pl
    port: 587
    username: ${SPRING_MAIL_USERNAME} # Config Vars z Heroku
    password: ${SPRING_MAIL_PASSWORD} # Config Vars z Heroku
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true

  datasource:
    url: ${DATABASE_URL} # Config Vars z Heroku
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

olx:
  client_id: ${OLX_CLIENT_ID} # Config Vars z Heroku
  client_secret: ${OLX_CLIENT_SECRET} # Config Vars z Heroku
  redirect_uri: ${OLX_REDIRECT_URI} # Config Vars z Heroku

mailersend:
  api:
    token: ${MAILERSEND_API_TOKEN} # Config Vars z Heroku

logging:
  level:
    root: DEBUG
    org.springframework.mail: TRACE
    org.springframework.boot.autoconfigure.mail: TRACE
